### PR TITLE
Added Euclid filters

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This PR addresses #47. I added the Euclid filters and some documentation.

### CODE REVIEW

**Comment by dkirkby** [comment]
@fjaviersanchez Can you check why the CI tests are failing?

**Comment by fjaviersanchez** [comment]
Yes, so resample is failing because for `numpy >= 1.16` the following happens:
```Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 

This code may break in numpy 1.16 because this will return a view instead of a copy -- see release notes for details.
  y_in = y_in.view(y_type).reshape(data_in.shape + y_shape)```

I'm working on a fix

**Comment by fjaviersanchez** [comment]
Okay, I think the tests will pass once we merge #49 and I rebase

**Comment by fjaviersanchez** [comment]
@dkirkby, I added coverage tests in python2.7 and 3.x but it says that the overall coverage decreased because it takes the average of both runs (py27 and py3x) and, since in py3x it doesn't run the line `from __future__ import print_function, division` it shows a smaller coverage... I think that the current criterion to approve the coverage is too restrictive but, do you have any suggestions to make one of the tests run the line that I mention above?

**Comment by fjaviersanchez** [comment]
I just made the coverage module ignore the `from __future__ import` line

**Pull request merged**
