### PR TITLE
fix basestring

### PR DESCRIPTION
**Pull request by londumas**
fix `basestring`, by replacing by `str`
Fix issue https://github.com/dkirkby/speclite/issues/26

### CODE REVIEW

**Comment by moustakas** [comment]
@dkirkby can we merge this one-line change?

**Comment by dkirkby** [comment]
I am looking at this now...  (won't this fix break on python 2.7?)

**Comment by dkirkby** [comment]
It looks like a proper fix involves updating a bunch of astropy support stuff and possibly dropping python 2.x support.  This might also be a good time to strip this package down to just the filter stuff, since the other algorithms in here never really matured to production level.

However, @moustakas if you can confirm that this one-line fix is useful to you in the near term, until I do the proper job, I will go ahead and merge now.

**Comment by moustakas** [comment]
> However, @moustakas if you can confirm that this one-line fix is useful to you in the near term, until I do the proper job, I will go ahead and merge now.

Yes, I have the identical one-line fix in my local checkout of the code.

**Comment by dkirkby** [comment]
Done!

**Pull request merged**
