### PR TITLE
Add new filters

### LINKED ISSUE #11: Add more filter responses
@moustakas has requested MzLS-z and Bok-g,r for DESI work.  This issue is to gather the data and include it in this package.  Are there any other filters we need soon?

### PR DESCRIPTION
**Pull request by dkirkby**
Add filter curves for MzLS-z, BASS-g and BASS-r:

desi_imaging

Fixes #11.

### CODE REVIEW

**Comment by dkirkby** [comment]
@moustakas @sbailey please check the following:
 - Do we want to trim some of the values below 1e-4, or keep everything?  (the costs are performance and convenience)
 - Any corrections / additions for the descriptions in the new ecsv files (e.g., [here](https://github.com/dkirkby/speclite/pull/37/files#diff-f0019ad99fb9c12149f1af8fb498fcaaR11)).

**Comment by dkirkby** [comment]
Travis tests are failing because they span numpy versions with different whitespace in their formatted output and I don't know how to tell doctest to do the right thing (even after trying `#doctest: +NORMALIZE_WHITESPACE`).

For example:
```
>>> print((result['flux'][:5]))
Expected:
    [ 0.5  0.5  0.5  0.5  0.5]
Got:
    [0.5 0.5 0.5 0.5 0.5]
```

Unless @weaverba137 knows the answer, I will remove these doctests (which seems a shame).

**Comment by weaverba137** [comment]
@dkirkby, what specific lines in what files have this issue?

**Comment by weaverba137** [comment]
PS, I've had success with `+NORMALIZE_WHITESPACE`.  I've also had success using `print()`.  However, I don't think I've done both at the same time.

**Comment by dkirkby** [comment]
@weaverba137 I tried both `print(...)` and `+NORMALIZE_WHITESPACE` (individually).

The 3 lines causing problems are `speclite/filters.py` #564 and `speclite/redshift.py` #40 and #56.  A sample travis failure log is [here](https://travis-ci.org/dkirkby/speclite/jobs/418804387).

**Comment by sbailey** [comment]
Let's go ahead and keep the full wavelength range as you currently have committed.  The tails don't seem excessive.  Comments in the metadata seem fine (though I haven't checked in detail).

**Comment by weaverba137** [comment]
I remember a fix now: make numpy print strings using 1.13 format.  See https://github.com/weaverba137/pydl/blob/master/pydl/__init__.py#L42.

**Pull request merged**
