### PR TITLE
Band shift

### PR DESCRIPTION
**Pull request by dkirkby**
This implementation assumes that the band shift parameter should be used to *redshift* a filter response curve.  However, it sounds like I need to change this to a *blueshift* but I will wait until the dust settles at #20 before making the final changes.

### CODE REVIEW

**Comment by dkirkby** [comment]
@moustakas I changed "redshift" to "band_shift" throughout and changed the transform from `wlen*(1+z)` to `wlen/(1+z)`, so I think this is now doing the same as kcorrect with the same notation.

**Comment by moustakas** [comment]
Fantastic.  I can do some spot-checks against k-correct and will report any issues but don't wait for me to merge.

**Comment by dkirkby** [comment]
@moustakas Please also check the updated docs [here](http://speclite.readthedocs.io/en/band_shift/api.html#shifted-filters) and [here](http://speclite.readthedocs.io/en/band_shift/api/speclite.filters.FilterResponse.html#speclite.filters.FilterResponse.create_shifted), when you have time, in case I screwed those up also.

**Comment by moustakas** [comment]
Documentation looks fine --

**Pull request merged**
