### PR TITLE
Calculate magnitudes in standard filters

### PR DESCRIPTION
**Pull request by dkirkby**
The new documentation for this branch describes the standard filters:

  http://speclite.readthedocs.org/en/9/filters.html

and the new `filters` module API:

  http://speclite.readthedocs.org/en/9/api.html#module-speclite.filters

The following `desisim` code:
```
rband = desisim.filterfunc.filterfunc(filtername='sdss_r0.txt')
maggies = rband.get_maggies(wlen, flux)
```
can now be implemented as:
```
rband = speclite.filters.load_filter('sdss2010-r')
maggies = rband.get_ab_maggies(flux, wlen)
```
The SDSS ugriz, WISE W1-4 and Johnson/Cousin UBVRI filters are already included, but I need some advice on what to use for DECam.

@moustakas @sbailey @weaverba137 The documentation and API are ready for a critical review now. Still on the TODO list:
* Write unit tests, in addition to those already in the docstrings.
* Look into how much the support for astropy units is hurting the performance and whether this matters.
* Add more filters. DECam is the highest priority, but other suggestions are welcome.

### CODE REVIEW

**Comment by weaverba137** [comment]
The *WISE* filter plot would be easier to read if the x-axis were linear.

**Comment by dkirkby** [comment]
I chose the log scaling and limits to match Fig.4 of the reference for these curves, but I agree that the default matplotlib axis labels are not very informative in this case.

**Comment by moustakas** [comment]
At a glance this looks *awesome*.  Note that the W4 filter is wrong by ~10% for star-forming galaxies because it's calibrated on a Raleigh-Jeans SED (see Sec 2.1.3 of http://adsabs.harvard.edu/abs/2014ApJS..212...18B) but that does not matter here.

One request: would it be possible to get the maggies / AB magnitudes for an entire group of filters simultaneously?  I see that speclite.filters.load_filter_group('sdss2010') returns a list of the filters belonging to that group, but wouldn't it be grand if we could do
```
sdss = speclite.filters.load_filter_group('sdss2010')
maggies = sdss.get_ab_maggies(flux, wlen)
```
(or some variation) with maggies an NFILT array?

**Comment by dkirkby** [comment]
Coverage is back to 100% after learning a few tricks to use temporary files and call matplotlib on TravisCI.

**Comment by dkirkby** [comment]
@weaverba137 I cleaned up the [WISE plot](http://speclite.readthedocs.org/en/9/filters.html#wise-filters) wavelength axis: it is still log scale (to match the paper) but now shows a useful number of axis labels, instead of just one.

**Comment by dkirkby** [comment]
@moustakas In your example, would you expect the return value to be a dictionary or a list of values?
```
maggies = sdss.get_ab_maggies(flux, wlen)
```

**Comment by moustakas** [comment]
I was thinking a list of values.

**Comment by dkirkby** [comment]
@moustakas For the W4 calibration issue, I propose to keep the original W4 definition, since that is the official WISE data product, and add the following note to the docs:

Note that these responses are based on pre-flight measurements but the in-flight responses of the W3 and W4 filters are observed to have effective wavelengths that differ by -(3-5)% and +(2-3)%, respectively.  Refer to Section 2.2 of [Wright 2010](http://dx.doi.org/10.1088/0004-6256/140/6/1868) for details. See also Section 2.1.3 of [Brown 2014] (http://dx.doi.org/10.1088/0067-0049/212/2/18) for further details about W4.

**Comment by moustakas** [comment]
Sounds good.

**Comment by dkirkby** [comment]
@moustakas I implemented your request and this now works:
```
sdss = speclite.filters.load_filters('sdss2010-*')
maggies = sdss.get_ab_maggies(flux, wlen)
```
I replaced the original `load_filter_group()` with a more powerful `load_filters()` to enable calculating magnitudes on multiple spectra in multiple filters from different groups:

  http://speclite.readthedocs.org/en/9/api/speclite.filters.load_filters.html#speclite.filters.load_filters

For example, to implement the ELG target selection cuts:
```
filters = speclite.filters.load_filters('decam-g', 'decam-r', 'decam-z', 'wise2010-W1', 'wise2010-W2')
mags = filters.get_ab_magnitudes(spectra, wlen)
selected = (mags['decam-r'] < 23.4) & (mags['decam-r']-mags['decam-z'] > 0.3) & ...
```
The return type of `get_ab_maggies()` and `get_ab_magnitudes()` for a set of filters is an astropy Table, which supports both array-like and dict-like access, and generalizes nicely when you pass an array of spectra:

  http://speclite.readthedocs.org/en/9/api/speclite.filters.FilterSequence.html

**Comment by dkirkby** [comment]
@sbailey I will be ready to merge this PR and release v0.3 soon, but let me know if you would like more time to review the API and docs before I go ahead.

@moustakas I added an easy way to work with filters that are not already included in the package:

  http://speclite.readthedocs.org/en/9/filters.html#custom-filters

I propose to use this mechanism for some of the filters you mentioned (Mayall-z, Bok, etc) so we can get work done now while figuring out exactly what to include in the package (which has long-term package size implications since git always clones the full history of a project).  If we can converge soon on DECam filter curves that DES endorses then I will include them in v0.3.

**Comment by sbailey** [comment]
It would be handy to have a programmatic way to discover what filters it knows about, e.g. something like speclite.filters.get_filter_names() and .get_filter_groups() or equivalent.

I appreciate that units are recommended but not required.  Thanks.

Otherwise looks good to me.  I wasn't able to break anything.

**Comment by dkirkby** [comment]
@moustakas I added the DECam filters from William Wester's 2014 spreadsheet, which he confirms is the most recent public data:

  http://speclite.readthedocs.org/en/9/filters.html#decam-filters

@sbailey I added a module-level `filter_group_names` attribute so you can now discover all available filters using:
```
>>> [ speclite.filters.load_filters(group + '-*').names
...     for group in speclite.filters.filter_group_names ]
[['sdss2010-u', 'sdss2010-g', 'sdss2010-r', 'sdss2010-i', 'sdss2010-z'],
 ['decam2014-u', 'decam2014-g', 'decam2014-r', 'decam2014-i', 'decam2014-z', 'decam2014-Y'], 
 ['wise2010-W1', 'wise2010-W2', 'wise2010-W3', 'wise2010-W4'],
 ['bessell-U', 'bessell-B', 'bessell-V', 'bessell-R', 'bessell-I']]
```

I spent some time profiling yesterday and discovered that astropy units can be really slow if you are not careful.  After removing some hotspots, magnitude calculations are 5x faster and the overhead from including units is only ~10%.  Also, where performance matters you can get ~10x speedups by calculating magnitudes for an array of spectra on the same wavelength grid with one call.

I will go ahead with the merge and version update once the travis tests finish.

**Pull request merged**
